<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>HomepagePage_txtProductDetail</name>
   <tag></tag>
   <elementGuidId>83eb274e-266e-4bc4-b63e-cdae8d3b1105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='inventory_item_container']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <type>Main</type>
      <value>//div[@id='inventory_item_container']</value>
      <webElementGuid>991bc347-d530-42ed-9bc8-ae0de40cdc1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
